# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_alpha <- function(x, lambda, omega) {
    .Call(`_mmBPFA_sample_alpha`, x, lambda, omega)
}

sample_gamma_k <- function(zeros, lambda, c = 0, d = 100) {
    .Call(`_mmBPFA_sample_gamma_k`, zeros, lambda, c, d)
}

sample_d <- function(zeros, gamma_k, c, c0, d0) {
    .Call(`_mmBPFA_sample_d`, zeros, gamma_k, c, c0, d0)
}

sample_IBP_a <- function(ibp_b, zeros, e = 1, f = 1) {
    .Call(`_mmBPFA_sample_IBP_a`, ibp_b, zeros, e, f)
}

sample_IBP_b <- function(ibp_a, ibp_b, zeros) {
    .Call(`_mmBPFA_sample_IBP_b`, ibp_a, ibp_b, zeros)
}

sample_lambda_and_zeros <- function(x, lambda, zeros, omega, alpha, gamma_k, dc, ibp_a, ibp_b, tau, sparse, infinite) {
    .Call(`_mmBPFA_sample_lambda_and_zeros`, x, lambda, zeros, omega, alpha, gamma_k, dc, ibp_a, ibp_b, tau, sparse, infinite)
}

sample_omega <- function(lambda, x, alpha) {
    .Call(`_mmBPFA_sample_omega`, lambda, x, alpha)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_mmBPFA_RcppExport_registerCCallable', PACKAGE = 'mmBPFA')
})
